[pytest]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
addopts = --ignore=tests/test_main.py
          --ignore=/tests/test_views.py
          --ignore=tests/test_logger.py